### ISSUE TITLE
CSV export format gives HTML for Collections

### ISSUE THREAD

**Issue by patrickmj** [utlib/CsvExport#1]
After your email, I looked more closely, and it is indeed an error message from xdebug.

<font size='1'><table class='xdebug-error xe-uncaught-exception' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Fatal error: Uncaught TypeError: Argument 1 passed to Table_ElementText::findByRecord() must be an instance of Omeka_Record_AbstractRecord, array given, called in /var/www/html/Omeka/plugins/CsvExport/helpers/CsvExportFunctions.php on line 34 and defined in /var/www/html/Omeka/application/models/Table/ElementText.php on line <i>41</i></th></tr>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> TypeError: Argument 1 passed to Table_ElementText::findByRecord() must be an instance of Omeka_Record_AbstractRecord, array given, called in /var/www/html/Omeka/plugins/CsvExport/helpers/CsvExportFunctions.php on line 34 in /var/www/html/Omeka/application/models/Table/ElementText.php on line <i>41</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0000</td><td bgcolor='#eeeeec' align='right'>362648</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='/var/www/html/Omeka/index.php' bgcolor='#eeeeec'>.../index.php<b>:</b>0</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>2</td><td bgcolor='#eeeeec' align='center'>0.0208</td><td bgcolor='#eeeeec' align='right'>2280104</td><td bgcolor='#eeeeec'>Omeka_Application->run(  )</td><td title='/var/www/html/Omeka/index.php' bgcolor='#eeeeec'>.../index.php<b>:</b>23</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>3</td><td bgcolor='#eeeeec' align='center'>0.0208</td><td bgcolor='#eeeeec' align='right'>2280104</td><td bgcolor='#eeeeec'>Zend_Application->run(  )</td><td title='/var/www/html/Omeka/application/libraries/Omeka/Application.php' bgcolor='#eeeeec'>.../Application.php<b>:</b>73</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>4</td><td bgcolor='#eeeeec' align='center'>0.0208</td><td bgcolor='#eeeeec' align='right'>2280104</td><td bgcolor='#eeeeec'>Zend_Application_Bootstrap_Bootstrap->run(  )</td><td title='/var/www/html/Omeka/application/libraries/Zend/Application.php' bgcolor='#eeeeec'>.../Application.php<b>:</b>384</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>5</td><td bgcolor='#eeeeec' align='center'>0.0208</td><td bgcolor='#eeeeec' align='right'>2280104</td><td bgcolor='#eeeeec'>Zend_Controller_Front->dispatch(  )</td><td title='/var/www/html/Omeka/application/libraries/Zend/Application/Bootstrap/Bootstrap.php' bgcolor='#eeeeec'>.../Bootstrap.php<b>:</b>105</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>6</td><td bgcolor='#eeeeec' align='center'>0.0215</td><td bgcolor='#eeeeec' align='right'>2367128</td><td bgcolor='#eeeeec'>Zend_Controller_Dispatcher_Standard->dispatch(  )</td><td title='/var/www/html/Omeka/application/libraries/Zend/Controller/Front.php' bgcolor='#eeeeec'>.../Front.php<b>:</b>954</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>7</td><td bgcolor='#eeeeec' align='center'>0.0241</td><td bgcolor='#eeeeec' align='right'>2429272</td><td bgcolor='#eeeeec'>Zend_Controller_Action->dispatch(  )</td><td title='/var/www/html/Omeka/application/libraries/Zend/Controller/Dispatcher/Standard.php' bgcolor='#eeeeec'>.../Standard.php<b>:</b>308</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>8</td><td bgcolor='#eeeeec' align='center'>0.0273</td><td bgcolor='#eeeeec' align='right'>2538560</td><td bgcolor='#eeeeec'>Zend_Controller_Action_HelperBroker->notifyPostDispatch(  )</td><td title='/var/www/html/Omeka/application/libraries/Zend/Controller/Action.php' bgcolor='#eeeeec'>.../Action.php<b>:</b>527</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>9</td><td bgcolor='#eeeeec' align='center'>0.0273</td><td bgcolor='#eeeeec' align='right'>2539304</td><td bgcolor='#eeeeec'>Zend_Controller_Action_Helper_ViewRenderer->postDispatch(  )</td><td title='/var/www/html/Omeka/application/libraries/Zend/Controller/Action/HelperBroker.php' bgcolor='#eeeeec'>.../HelperBroker.php<b>:</b>277</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>10</td><td bgcolor='#eeeeec' align='center'>0.0273</td><td bgcolor='#eeeeec' align='right'>2539304</td><td bgcolor='#eeeeec'>Zend_Controller_Action_Helper_ViewRenderer->render(  )</td><td title='/var/www/html/Omeka/application/libraries/Zend/Controller/Action/Helper/ViewRenderer.php' bgcolor='#eeeeec'>.../ViewRenderer.php<b>:</b>972</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>11</td><td bgcolor='#eeeeec' align='center'>0.0275</td><td bgcolor='#eeeeec' align='right'>2539384</td><td bgcolor='#eeeeec'>Zend_Controller_Action_Helper_ViewRenderer->renderScript(  )</td><td title='/var/www/html/Omeka/application/libraries/Zend/Controller/Action/Helper/ViewRenderer.php' bgcolor='#eeeeec'>.../ViewRenderer.php<b>:</b>933</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>12</td><td bgcolor='#eeeeec' align='center'>0.0275</td><td bgcolor='#eeeeec' align='right'>2539384</td><td bgcolor='#eeeeec'>Zend_View_Abstract->render(  )</td><td title='/var/www/html/Omeka/application/libraries/Zend/Controller/Action/Helper/ViewRenderer.php' bgcolor='#eeeeec'>.../ViewRenderer.php<b>:</b>912</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>13</td><td bgcolor='#eeeeec' align='center'>0.0277</td><td bgcolor='#eeeeec' align='right'>2555944</td><td bgcolor='#eeeeec'>Omeka_View->_run(  )</td><td title='/var/www/html/Omeka/application/libraries/Zend/View/Abstract.php' bgcolor='#eeeeec'>.../Abstract.php<b>:</b>888</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>14</td><td bgcolor='#eeeeec' align='center'>0.0281</td><td bgcolor='#eeeeec' align='right'>2562672</td><td bgcolor='#eeeeec'>include( <font color='#00bb00'>'/var/www/html/Omeka/plugins/CsvExport/views/shared/items/browse.csv.php'</font> )</td><td title='/var/www/html/Omeka/application/libraries/Omeka/View.php' bgcolor='#eeeeec'>.../View.php<b>:</b>114</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>15</td><td bgcolor='#eeeeec' align='center'>0.0391</td><td bgcolor='#eeeeec' align='right'>2576328</td><td bgcolor='#eeeeec'>printCsvExport(  )</td><td title='/var/www/html/Omeka/plugins/CsvExport/views/shared/items/browse.csv.php' bgcolor='#eeeeec'>.../browse.csv.php<b>:</b>8</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>16</td><td bgcolor='#eeeeec' align='center'>0.0934</td><td bgcolor='#eeeeec' align='right'>2876448</td><td bgcolor='#eeeeec'>getCsvRow(  )</td><td title='/var/www/html/Omeka/plugins/CsvExport/helpers/CsvExportFunctions.php' bgcolor='#eeeeec'>.../CsvExportFunctions.php<b>:</b>103</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>17</td><td bgcolor='#eeeeec' align='center'>0.0934</td><td bgcolor='#eeeeec' align='right'>2876448</td><td bgcolor='#eeeeec'>Table_ElementText->findByRecord(  )</td><td title='/var/www/html/Omeka/plugins/CsvExport/helpers/CsvExportFunctions.php' bgcolor='#eeeeec'>.../CsvExportFunctions.php<b>:</b>34</td></tr>
</table></font>

**Comment by dicksonlaw583** [comment]
@patrickmj:

I've pushed up a patch for this issue in the branch ```fix-issue-1``` (#5). Can you test it?

**Comment by patrickmj** [comment]
Yep, that looks like it does the trick. thanks!
