### ISSUE TITLE
When exporting, if a metadata field has multiple values, only the 1st value is exported

### ISSUE THREAD

**Issue by cherveny** [utlib/CsvExport#11]
For instance, we use multiple subjects per item.  Exporting to CSV, only the first subject is given, the rest are dropped.  Ideally, would be treated like tags, where they are separated by a known character

**Comment by dicksonlaw583** [comment]
Can you try this new branch and comment on the PR?

https://github.com/utlib/CsvExport/tree/fix-multi-text

We've identified the default sequence used in CSV Import as the element separator (it was ```^^```), so it should work as-is when "Use an export from Omeka CSV Report" is checked.

**Comment by cherveny** [comment]
Will do, thank you the fix.  It may be a little while before I can test, due to a busy schedule, but will let you know as soon as I am able to test.

**Comment by cherveny** [comment]
Getting some odd behavior.  If I export, then try using omeka format selected in the import, it states The following problems were found with your CSV file and Omeka installation.

Usually, these are the result of the elements in your Omeka.net site not having corresponding elements in this installation of Omeka. Either the Dublin Core Extended plugin is not installed, or you created custom item type elements in Omeka.net, but have not yet created them here.

Please correct the errors, then try your import again.  

This is importing the same items that are already within a collection, same item type, etc, thus you'd think we should have all fields needed already defined.

**Comment by cherveny** [comment]
Also, if you try to import as non omeka format, it requires a single character for separator for multiple items within a field, it won't let you enter ^^ because of this.

**Comment by dicksonlaw583** [comment]
@cherveny:

What version is your CSV importer? I've tested on 2.0.4 and the ^^ convention worked there.

On an added note, Excel seems to be turning CSV files into tab-separated data if you just Ctrl+S after editing. Please use Save As and verify that the commas are still there with Notepad.

**Comment by cherveny** [comment]
Will check at work tomorrow.  Was able to find a work around.   Exported,
did find/replace of double carrot to single bar, then set tag separator to
bar (Even though these aren't tags).  Worked like a charm.

Learned the hard way not to use Excel.  Excel doesn't handle Unicode
diacritics well.  Instead used librecalc which handles the text and
preserves the special characters.

**Comment by cherveny** [comment]
2.0.4
