### ISSUE TITLE
Omeka site has old version of plugin

### ISSUE THREAD

**Issue by plutotom** [utlib/CsvExport#16]
The plugin downloaded from here https://omeka.org/classic/plugins/CsvExport/ throws an error shared below.
The latest version on GitHub works great!

Fatal error: Uncaught TypeError: join(): Argument #2 ($array) must be of type ?array, string given in /Applications/XAMPP/xamppfiles/htdocs/omeka/plugins/CsvExport/helpers/CsvExportFunctions.php:70 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/omeka/plugins/CsvExport/helpers/CsvExportFunctions.php(70): join(Array, ',') #1 /Applications/XAMPP/xamppfiles/htdocs/omeka/plugins/CsvExport/helpers/CsvExportFunctions.php(110): getCsvRow(Object(Item), Array) #2 /Applications/XAMPP/xamppfiles/htdocs/omeka/plugins/CsvExport/views/shared/items/browse.csv.php(8): printCsvExport(Array) #3 /Applications/XAMPP/xamppfiles/htdocs/omeka/application/libraries/Omeka/View.php(114): include('/Applications/X...') #4 /Applications/XAMPP/xamppfiles/htdocs/omeka/application/libraries/Zend/View/Abstract.php(888): Omeka_View->_run('/Applications/X...') #5 /Applications/XAMPP/xamppfiles/htdocs/omeka/application/libraries/Zend/Controller/Action/Helper/ViewRenderer.php(912): Zend_View_Abstract->render(NULL) #6 /Applications/XAMPP/xamppfiles/htdocs/omeka/application/libraries/Zend/Controller/Action/Helper/ViewRenderer.php(933): Zend_Controller_Action_Helper_ViewRenderer->renderScript('items/browse.cs...', NULL) #7 /Applications/XAMPP/xamppfiles/htdocs/omeka/application/libraries/Zend/Controller/Action/Helper/ViewRenderer.php(972): Zend_Controller_Action_Helper_ViewRenderer->render() #8 /Applications/XAMPP/xamppfiles/htdocs/omeka/application/libraries/Zend/Controller/Action/HelperBroker.php(277): Zend_Controller_Action_Helper_ViewRenderer->postDispatch() #9 /Applications/XAMPP/xamppfiles/htdocs/omeka/application/libraries/Zend/Controller/Action.php(527): Zend_Controller_Action_HelperBroker->notifyPostDispatch() #10 /Applications/XAMPP/xamppfiles/htdocs/omeka/application/libraries/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('browseAction') #11 /Applications/XAMPP/xamppfiles/htdocs/omeka/application/libraries/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http)) #12 /Applications/XAMPP/xamppfiles/htdocs/omeka/application/libraries/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch() #13 /Applications/XAMPP/xamppfiles/htdocs/omeka/application/libraries/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run() #14 /Applications/XAMPP/xamppfiles/htdocs/omeka/application/libraries/Omeka/Application.php(73): Zend_Application->run() #15 /Applications/XAMPP/xamppfiles/htdocs/omeka/admin/index.php(28): Omeka_Application->run() #16 {main} thrown in /Applications/XAMPP/xamppfiles/htdocs/omeka/plugins/CsvExport/helpers/CsvExportFunctions.php on line 70

**Comment by dicksonlaw583** [comment]
I have put up a new release, and it should show up on the official Omeka site soon. If it does not update, I will follow-up with them.
