### ISSUE TITLE
files column and 'original_filename' vs. 'uri'

### ISSUE THREAD

**Issue by patrickmj** [utlib/CsvExport#2]
Currently, the files column produced could produce urls to external sources, rather than what's pulled in to Omeka.

The `original_filename` column on the Files table stores the best URL Omeka can guess for the file origin. When it is uploaded from the admin screen, it's just the URL to Omeka's internal storage. But, if it is imported from elsewhere via one of the various import plugins, it could refer to something external to Omeka.

It's a tricky call, whether to report that external one, since it is the 'canonical' URL, vs. whether to report the one that's 'native' to Omeka. It's a good archival theory question about canonical vs copies. What Omeka stores as the 'original' as far as it is concerned, is just a copy of that external 'canonical'.

On one hand, the external canonical will make sense in lots of situations. On another hand, there's no guarantee that an external resource will be stable later. Thus, for a CSV export from an Omeka site, I lean a little toward pulling the files from Omeka just for that stability and consistency of what's being exported.

The option would be nice -- do an export using external references, see if it works; do another using internal references, see if it works. Sounds easy enough.

You can also dig up the different URLs using `metadata()`

```php
<?php echo metadata($file, 'uri'); ?>
```
for the Omeka-native file URL,

or

```php
<?php echo metadata($file, 'original_filename''); ?>

```
for the external URL

All kinds of options!

**Comment by dicksonlaw583** [comment]
@patrickmj:

I have pushed up a branch that adds the configuration option mentioned in our discussion. Can you try it out? This is scheduled to go into 1.0.1 along with #1.

**Comment by patrickmj** [comment]
Looks good to me. thanks!
