### ISSUE TITLE
Only 200 Records are exported

### ISSUE THREAD

**Issue by DigArk** [utlib/CsvExport#7]
We just installed CSVExport 1.01 on Omeka 2.5.1, OS X Darwin 14.5.0 x86_64, MySQL 5.6.14  and PHP 5.5.38 (apache2handler)

We have 14,000+ items and we select all items and export to csv. The resulting file only contains the records displayed on the page not all the selected records (200)

Thanks

**Comment by WaltRiceJr** [comment]
This is an easy change. In the CsvExportPlugin.php file, add 'items_browse_per_page' to the filters list:

```
    protected $_filters = array(
        'response_contexts',
        'action_contexts',
        'items_browse_per_page',
    );
```

Add the following function within the class:

```
    public function filterItemsBrowsePerPage($perPage, $args) {
        if( $_GET["output"] == 'csv'){
            $perPage=null; // no pagination
        }
        return $perPage;
    }

```

**Comment by dicksonlaw583** [comment]
@WaltRiceJr 

Small correction for getting rid of the PHP warning:

```
public function filterItemsBrowsePerPage($perPage, $args) {
    if(isset($_GET['output']) && $_GET['output'] == 'csv') {
        $perPage = null;
    }
    return $perPage;
}
```

**Comment by gnosisgithub** [comment]
I do not see how to accomplish the bulk export. I only see how to export on the item level. Can you share how?

**Comment by dicksonlaw583** [comment]
Closing because a full export on that scale is likely to time out or crash. Please export by other means or patch manually if small enough on a specific setup.

**Comment by andrisi** [comment]
Could you make an option to try to export all items in one go, so that no hacks like above are needed? Without this the pluging is not really useful for its intended purpose. Thanks!

**Comment by andrisi** [comment]
Another temporary fix, without hacking into the source code is to set the nomber of items displayed per page for the site to a high number. For me 3000 worked just fine.
