### ISSUE TITLE
export empty file

### ISSUE THREAD

**Issue by whisere** [utlib/CsvExport#8]
installed the plugin successfully under omeka 2.5.1, but export empty csv files in all pages (items, item, collection)

under redhat 7, php 5.4 and 5.5.52-MariaDB MariaDB  

Thanks!

**Comment by whisere** [comment]
And no error is reported in php log or omeka log.

**Comment by whisere** [comment]
re-downloaded the plugins and  made the following change to CsvExport/helpers/CsvExportFunctions.php, it is working now:
not sure why "\0" is causing problem and the need for it.
a unchanged version under different os works fine

// Header: Write it in
    //fputcsv($f, $headerEntries, ',', '"', "\0");
   fputcsv($f, $headerEntries, ',', '"');
    // Body
    foreach ($items as $item) {
        //fputcsv($f, getCsvRow($item, $elements), ',', '"', "\0");
        fputcsv($f, getCsvRow($item, $elements), ',', '"');
    }
//add this at the end to release $f
  fclose($f);

**Comment by dicksonlaw583** [comment]
That's odd. On my Ubuntu 14.04 LTS (PHP 5.5.9), not having the \0 there gave me this warning:
 
```Warning: fputcsv(): escape must be a character```
 
Can you provide the PHP version of the "different OS" you were using that worked with the unmodified plugin? I'm planning to sniff the PHP version if there is a change in this function between 5.4 and 5.5.

**Comment by whisere** [comment]
The other version is PHP version: 7.0.15  MySQL: 5.6.35

**Comment by dicksonlaw583** [comment]
@whisere:

Can you try the new ```fix-rhel7``` branch on both setups?

https://github.com/utlib/CsvExport/tree/fix-rhel7

**Comment by whisere** [comment]
Has only https://raw.githubusercontent.com/utlib/CsvExport/fix-rhel7/helpers/CsvExportFunctions.php been changed?
I replaced this file in both version, it works!

**Comment by whisere** [comment]
might be a good idea to add this fclose($f); at the end?

**Comment by dicksonlaw583** [comment]
@whisere:

Yes, ```helpers/CsvExportFunctions.php``` is the only changed file, you haven't missed anything.

Good catch, by the way, I've added your suggestion to the branch.

**Comment by whisere** [comment]
Thanks!

**Comment by dicksonlaw583** [comment]
Resolved by #9, closing.
